# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\cguis\design\main_window.ui'
#
# Created by: PySide2 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setWindowTitle("MainWindow")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setObjectName("central_widget")
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.result_dock_widget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_dock_widget.sizePolicy().hasHeightForWidth())
        self.result_dock_widget.setSizePolicy(sizePolicy)
        self.result_dock_widget.setMinimumSize(QtCore.QSize(400, 125))
        self.result_dock_widget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.result_dock_widget.setObjectName("result_dock_widget")
        self.result_dock_contents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_dock_contents.sizePolicy().hasHeightForWidth())
        self.result_dock_contents.setSizePolicy(sizePolicy)
        self.result_dock_contents.setObjectName("result_dock_contents")
        self.result_dock_widget.setWidget(self.result_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.result_dock_widget)
        self.rule_dock_widget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rule_dock_widget.sizePolicy().hasHeightForWidth())
        self.rule_dock_widget.setSizePolicy(sizePolicy)
        self.rule_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.rule_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.rule_dock_widget.setObjectName("rule_dock_widget")
        self.rule_dock_contents = QtWidgets.QWidget()
        self.rule_dock_contents.setObjectName("rule_dock_contents")
        self.rule_dock_widget.setWidget(self.rule_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.rule_dock_widget)
        self.operation_dock_widget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation_dock_widget.sizePolicy().hasHeightForWidth())
        self.operation_dock_widget.setSizePolicy(sizePolicy)
        self.operation_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.operation_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.operation_dock_widget.setObjectName("operation_dock_widget")
        self.operation_dock_contents = QtWidgets.QWidget()
        self.operation_dock_contents.setObjectName("operation_dock_contents")
        self.operation_dock_widget.setWidget(self.operation_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.operation_dock_widget)
        self.script_dock_widget = QtWidgets.QDockWidget(MainWindow)
        self.script_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.script_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.script_dock_widget.setObjectName("script_dock_widget")
        self.script_dock_contents = QtWidgets.QWidget()
        self.script_dock_contents.setObjectName("script_dock_contents")
        self.script_dock_widget.setWidget(self.script_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.script_dock_widget)
        self.mode_dock_widget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_dock_widget.sizePolicy().hasHeightForWidth())
        self.mode_dock_widget.setSizePolicy(sizePolicy)
        self.mode_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.mode_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.mode_dock_widget.setObjectName("mode_dock_widget")
        self.mode_dock_contents = QtWidgets.QWidget()
        self.mode_dock_contents.setObjectName("mode_dock_contents")
        self.mode_dock_widget.setWidget(self.mode_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.mode_dock_widget)
        self.channel_dock_widget = QtWidgets.QDockWidget(MainWindow)
        self.channel_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.channel_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.channel_dock_widget.setObjectName("channel_dock_widget")
        self.channel_dock_contents = QtWidgets.QWidget()
        self.channel_dock_contents.setObjectName("channel_dock_contents")
        self.channel_dock_widget.setWidget(self.channel_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.channel_dock_widget)
        self.transformation_dock_widget = QtWidgets.QDockWidget(MainWindow)
        self.transformation_dock_widget.setMinimumSize(QtCore.QSize(165, 90))
        self.transformation_dock_widget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.transformation_dock_widget.setObjectName("transformation_dock_widget")
        self.transformation_dock_contents = QtWidgets.QWidget()
        self.transformation_dock_contents.setObjectName("transformation_dock_contents")
        self.transformation_dock_widget.setWidget(self.transformation_dock_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.transformation_dock_widget)
        self.toolbar = QtWidgets.QToolBar(MainWindow)
        self.toolbar.setIconSize(QtCore.QSize(60, 60))
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolbar)
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCreate = QtWidgets.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionLocate = QtWidgets.QAction(MainWindow)
        self.actionLocate.setObjectName("actionLocate")
        self.actionDerive = QtWidgets.QAction(MainWindow)
        self.actionDerive.setObjectName("actionDerive")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHomepage = QtWidgets.QAction(MainWindow)
        self.actionHomepage.setObjectName("actionHomepage")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRule = QtWidgets.QAction(MainWindow)
        self.actionRule.setCheckable(True)
        self.actionRule.setChecked(True)
        self.actionRule.setObjectName("actionRule")
        self.actionChannel = QtWidgets.QAction(MainWindow)
        self.actionChannel.setCheckable(True)
        self.actionChannel.setChecked(True)
        self.actionChannel.setObjectName("actionChannel")
        self.actionOperation = QtWidgets.QAction(MainWindow)
        self.actionOperation.setCheckable(True)
        self.actionOperation.setChecked(True)
        self.actionOperation.setObjectName("actionOperation")
        self.actionMode = QtWidgets.QAction(MainWindow)
        self.actionMode.setCheckable(True)
        self.actionMode.setChecked(True)
        self.actionMode.setObjectName("actionMode")
        self.actionTransformation = QtWidgets.QAction(MainWindow)
        self.actionTransformation.setCheckable(True)
        self.actionTransformation.setChecked(True)
        self.actionTransformation.setObjectName("actionTransformation")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setCheckable(True)
        self.actionResult.setChecked(True)
        self.actionResult.setObjectName("actionResult")
        self.actionAttach = QtWidgets.QAction(MainWindow)
        self.actionAttach.setObjectName("actionAttach")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionWheel = QtWidgets.QAction(MainWindow)
        self.actionWheel.setObjectName("actionWheel")
        self.actionBoard = QtWidgets.QAction(MainWindow)
        self.actionBoard.setObjectName("actionBoard")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionDepot = QtWidgets.QAction(MainWindow)
        self.actionDepot.setObjectName("actionDepot")
        self.actionScript = QtWidgets.QAction(MainWindow)
        self.actionScript.setCheckable(True)
        self.actionScript.setChecked(True)
        self.actionScript.setObjectName("actionScript")
        self.actionAll = QtWidgets.QAction(MainWindow)
        self.actionAll.setObjectName("actionAll")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCreate)
        self.menuEdit.addAction(self.actionLocate)
        self.menuEdit.addAction(self.actionDerive)
        self.menuEdit.addAction(self.actionAttach)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSettings)
        self.menuWindow.addAction(self.actionRule)
        self.menuWindow.addAction(self.actionChannel)
        self.menuWindow.addAction(self.actionOperation)
        self.menuWindow.addAction(self.actionScript)
        self.menuWindow.addAction(self.actionMode)
        self.menuWindow.addAction(self.actionTransformation)
        self.menuWindow.addAction(self.actionResult)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionAll)
        self.menuHelp.addAction(self.actionHomepage)
        self.menuHelp.addAction(self.actionUpdate)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionInfo)
        self.menuView.addAction(self.actionWheel)
        self.menuView.addAction(self.actionImage)
        self.menuView.addAction(self.actionBoard)
        self.menuView.addAction(self.actionDepot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.result_dock_widget.setToolTip(_translate("MainWindow", "Result."))
        self.result_dock_widget.setStatusTip(_translate("MainWindow", "Result."))
        self.result_dock_widget.setWindowTitle(_translate("MainWindow", "Result"))
        self.rule_dock_widget.setToolTip(_translate("MainWindow", "Rule."))
        self.rule_dock_widget.setStatusTip(_translate("MainWindow", "Rule."))
        self.rule_dock_widget.setWindowTitle(_translate("MainWindow", "Rule"))
        self.operation_dock_widget.setToolTip(_translate("MainWindow", "Operation."))
        self.operation_dock_widget.setStatusTip(_translate("MainWindow", "Operation."))
        self.operation_dock_widget.setWindowTitle(_translate("MainWindow", "Operation"))
        self.script_dock_widget.setToolTip(_translate("MainWindow", "Script."))
        self.script_dock_widget.setStatusTip(_translate("MainWindow", "Script."))
        self.script_dock_widget.setWindowTitle(_translate("MainWindow", "Script"))
        self.mode_dock_widget.setToolTip(_translate("MainWindow", "Mode."))
        self.mode_dock_widget.setStatusTip(_translate("MainWindow", "Mode."))
        self.mode_dock_widget.setWindowTitle(_translate("MainWindow", "Mode"))
        self.channel_dock_widget.setToolTip(_translate("MainWindow", "Channel."))
        self.channel_dock_widget.setStatusTip(_translate("MainWindow", "Channel."))
        self.channel_dock_widget.setWindowTitle(_translate("MainWindow", "Channel"))
        self.transformation_dock_widget.setToolTip(_translate("MainWindow", "Transformation."))
        self.transformation_dock_widget.setStatusTip(_translate("MainWindow", "Transformation."))
        self.transformation_dock_widget.setWindowTitle(_translate("MainWindow", "Transformation"))
        self.toolbar.setWindowTitle(_translate("MainWindow", "ToolBar"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionImport.setStatusTip(_translate("MainWindow", "Import."))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setStatusTip(_translate("MainWindow", "Export."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setStatusTip(_translate("MainWindow", "Quit."))
        self.actionCreate.setText(_translate("MainWindow", "Create"))
        self.actionCreate.setStatusTip(_translate("MainWindow", "Create."))
        self.actionLocate.setText(_translate("MainWindow", "Locate"))
        self.actionLocate.setStatusTip(_translate("MainWindow", "Locate."))
        self.actionDerive.setText(_translate("MainWindow", "Derive"))
        self.actionDerive.setStatusTip(_translate("MainWindow", "Derive."))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSettings.setStatusTip(_translate("MainWindow", "Settings."))
        self.actionHomepage.setText(_translate("MainWindow", "Homepage"))
        self.actionHomepage.setStatusTip(_translate("MainWindow", "Homepage."))
        self.actionUpdate.setText(_translate("MainWindow", "Update"))
        self.actionUpdate.setStatusTip(_translate("MainWindow", "Update."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About."))
        self.actionRule.setText(_translate("MainWindow", "Rule"))
        self.actionRule.setStatusTip(_translate("MainWindow", "Rule."))
        self.actionChannel.setText(_translate("MainWindow", "Channel"))
        self.actionChannel.setStatusTip(_translate("MainWindow", "Channel."))
        self.actionOperation.setText(_translate("MainWindow", "Operation"))
        self.actionOperation.setStatusTip(_translate("MainWindow", "Operation."))
        self.actionMode.setText(_translate("MainWindow", "Mode"))
        self.actionMode.setStatusTip(_translate("MainWindow", "Mode."))
        self.actionTransformation.setText(_translate("MainWindow", "Transformation"))
        self.actionTransformation.setStatusTip(_translate("MainWindow", "Transformation."))
        self.actionResult.setText(_translate("MainWindow", "Result"))
        self.actionResult.setStatusTip(_translate("MainWindow", "Result."))
        self.actionAttach.setText(_translate("MainWindow", "Attach"))
        self.actionAttach.setStatusTip(_translate("MainWindow", "Attach."))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save."))
        self.actionWheel.setText(_translate("MainWindow", "Wheel"))
        self.actionWheel.setStatusTip(_translate("MainWindow", "Wheel."))
        self.actionBoard.setText(_translate("MainWindow", "Board"))
        self.actionBoard.setStatusTip(_translate("MainWindow", "Board."))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionImage.setStatusTip(_translate("MainWindow", "Image."))
        self.actionDepot.setText(_translate("MainWindow", "Depot"))
        self.actionDepot.setStatusTip(_translate("MainWindow", "Depot."))
        self.actionScript.setText(_translate("MainWindow", "Script"))
        self.actionScript.setStatusTip(_translate("MainWindow", "Script."))
        self.actionAll.setText(_translate("MainWindow", "All"))
        self.actionAll.setStatusTip(_translate("MainWindow", "All."))
        self.actionInfo.setText(_translate("MainWindow", "Support"))


