# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\main\python\cguis\design\settings_dialog.ui'
#
# Created by: PySide2 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(560, 600)
        SettingsDialog.setMinimumSize(QtCore.QSize(560, 0))
        SettingsDialog.setWindowTitle("Dialog")
        self.gridLayout = QtWidgets.QGridLayout(SettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.setti_items = QtWidgets.QTabWidget(SettingsDialog)
        self.setti_items.setTabPosition(QtWidgets.QTabWidget.North)
        self.setti_items.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.setti_items.setDocumentMode(False)
        self.setti_items.setObjectName("setti_items")
        self.setti_interface = QtWidgets.QWidget()
        self.setti_interface.setObjectName("setti_interface")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.setti_interface)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.setti_scroll_area = QtWidgets.QScrollArea(self.setti_interface)
        self.setti_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.setti_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.setti_scroll_area.setWidgetResizable(True)
        self.setti_scroll_area.setObjectName("setti_scroll_area")
        self.setti_scroll_contents = QtWidgets.QWidget()
        self.setti_scroll_contents.setGeometry(QtCore.QRect(0, 0, 527, 543))
        self.setti_scroll_contents.setObjectName("setti_scroll_contents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.setti_scroll_contents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.interface_general_window_gbox = QtWidgets.QGroupBox(self.setti_scroll_contents)
        self.interface_general_window_gbox.setObjectName("interface_general_window_gbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.interface_general_window_gbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.positive_wid_label = QtWidgets.QLabel(self.interface_general_window_gbox)
        self.positive_wid_label.setMinimumSize(QtCore.QSize(200, 25))
        self.positive_wid_label.setMaximumSize(QtCore.QSize(400, 40))
        self.positive_wid_label.setObjectName("positive_wid_label")
        self.gridLayout_3.addWidget(self.positive_wid_label, 0, 0, 1, 1)
        self.positive_wid_sp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.positive_wid_sp.setMinimumSize(QtCore.QSize(60, 25))
        self.positive_wid_sp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.positive_wid_sp.setMaximum(20)
        self.positive_wid_sp.setObjectName("positive_wid_sp")
        self.gridLayout_3.addWidget(self.positive_wid_sp, 0, 1, 1, 1)
        self.negative_wid_label = QtWidgets.QLabel(self.interface_general_window_gbox)
        self.negative_wid_label.setMinimumSize(QtCore.QSize(200, 25))
        self.negative_wid_label.setMaximumSize(QtCore.QSize(400, 40))
        self.negative_wid_label.setObjectName("negative_wid_label")
        self.gridLayout_3.addWidget(self.negative_wid_label, 1, 0, 1, 1)
        self.negative_wid_sp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.negative_wid_sp.setMinimumSize(QtCore.QSize(60, 25))
        self.negative_wid_sp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.negative_wid_sp.setMaximum(20)
        self.negative_wid_sp.setObjectName("negative_wid_sp")
        self.gridLayout_3.addWidget(self.negative_wid_sp, 1, 1, 1, 1)
        self.positive_color_label = QtWidgets.QLabel(self.interface_general_window_gbox)
        self.positive_color_label.setMinimumSize(QtCore.QSize(200, 25))
        self.positive_color_label.setMaximumSize(QtCore.QSize(400, 40))
        self.positive_color_label.setObjectName("positive_color_label")
        self.gridLayout_3.addWidget(self.positive_color_label, 2, 0, 1, 1)
        self.positive_color_0_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.positive_color_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.positive_color_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.positive_color_0_dp.setMaximum(255)
        self.positive_color_0_dp.setProperty("value", 0)
        self.positive_color_0_dp.setObjectName("positive_color_0_dp")
        self.gridLayout_3.addWidget(self.positive_color_0_dp, 2, 1, 1, 1)
        self.positive_color_1_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.positive_color_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.positive_color_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.positive_color_1_dp.setMaximum(255)
        self.positive_color_1_dp.setProperty("value", 0)
        self.positive_color_1_dp.setObjectName("positive_color_1_dp")
        self.gridLayout_3.addWidget(self.positive_color_1_dp, 2, 2, 1, 1)
        self.positive_color_2_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.positive_color_2_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.positive_color_2_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.positive_color_2_dp.setMaximum(255)
        self.positive_color_2_dp.setProperty("value", 0)
        self.positive_color_2_dp.setObjectName("positive_color_2_dp")
        self.gridLayout_3.addWidget(self.positive_color_2_dp, 2, 3, 1, 1)
        self.negative_color_label = QtWidgets.QLabel(self.interface_general_window_gbox)
        self.negative_color_label.setMinimumSize(QtCore.QSize(200, 25))
        self.negative_color_label.setMaximumSize(QtCore.QSize(400, 40))
        self.negative_color_label.setObjectName("negative_color_label")
        self.gridLayout_3.addWidget(self.negative_color_label, 3, 0, 1, 1)
        self.negative_color_0_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.negative_color_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.negative_color_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.negative_color_0_dp.setMaximum(255)
        self.negative_color_0_dp.setProperty("value", 0)
        self.negative_color_0_dp.setObjectName("negative_color_0_dp")
        self.gridLayout_3.addWidget(self.negative_color_0_dp, 3, 1, 1, 1)
        self.negative_color_1_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.negative_color_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.negative_color_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.negative_color_1_dp.setMaximum(255)
        self.negative_color_1_dp.setProperty("value", 0)
        self.negative_color_1_dp.setObjectName("negative_color_1_dp")
        self.gridLayout_3.addWidget(self.negative_color_1_dp, 3, 2, 1, 1)
        self.negative_color_2_dp = QtWidgets.QSpinBox(self.interface_general_window_gbox)
        self.negative_color_2_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.negative_color_2_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.negative_color_2_dp.setMaximum(255)
        self.negative_color_2_dp.setProperty("value", 0)
        self.negative_color_2_dp.setObjectName("negative_color_2_dp")
        self.gridLayout_3.addWidget(self.negative_color_2_dp, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.interface_general_window_gbox)
        self.interface_wheel_window_gbox = QtWidgets.QGroupBox(self.setti_scroll_contents)
        self.interface_wheel_window_gbox.setObjectName("interface_wheel_window_gbox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.interface_wheel_window_gbox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cubic_ratio_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.cubic_ratio_label.setMinimumSize(QtCore.QSize(200, 25))
        self.cubic_ratio_label.setMaximumSize(QtCore.QSize(400, 40))
        self.cubic_ratio_label.setObjectName("cubic_ratio_label")
        self.gridLayout_4.addWidget(self.cubic_ratio_label, 0, 0, 1, 1)
        self.cubic_ratio_dp = QtWidgets.QDoubleSpinBox(self.interface_wheel_window_gbox)
        self.cubic_ratio_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.cubic_ratio_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cubic_ratio_dp.setMinimum(0.0)
        self.cubic_ratio_dp.setMaximum(1.0)
        self.cubic_ratio_dp.setSingleStep(0.1)
        self.cubic_ratio_dp.setProperty("value", 0.0)
        self.cubic_ratio_dp.setObjectName("cubic_ratio_dp")
        self.gridLayout_4.addWidget(self.cubic_ratio_dp, 0, 1, 1, 1)
        self.wheel_ratio_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.wheel_ratio_label.setMinimumSize(QtCore.QSize(200, 25))
        self.wheel_ratio_label.setMaximumSize(QtCore.QSize(400, 40))
        self.wheel_ratio_label.setObjectName("wheel_ratio_label")
        self.gridLayout_4.addWidget(self.wheel_ratio_label, 1, 0, 1, 1)
        self.wheel_ratio_dp = QtWidgets.QDoubleSpinBox(self.interface_wheel_window_gbox)
        self.wheel_ratio_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.wheel_ratio_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wheel_ratio_dp.setMinimum(0.0)
        self.wheel_ratio_dp.setMaximum(1.0)
        self.wheel_ratio_dp.setSingleStep(0.1)
        self.wheel_ratio_dp.setProperty("value", 0.0)
        self.wheel_ratio_dp.setObjectName("wheel_ratio_dp")
        self.gridLayout_4.addWidget(self.wheel_ratio_dp, 1, 1, 1, 1)
        self.volum_ratio_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.volum_ratio_label.setMinimumSize(QtCore.QSize(200, 25))
        self.volum_ratio_label.setMaximumSize(QtCore.QSize(400, 40))
        self.volum_ratio_label.setObjectName("volum_ratio_label")
        self.gridLayout_4.addWidget(self.volum_ratio_label, 2, 0, 1, 1)
        self.volum_ratio_dp = QtWidgets.QDoubleSpinBox(self.interface_wheel_window_gbox)
        self.volum_ratio_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.volum_ratio_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.volum_ratio_dp.setMinimum(0.0)
        self.volum_ratio_dp.setMaximum(1.0)
        self.volum_ratio_dp.setSingleStep(0.1)
        self.volum_ratio_dp.setProperty("value", 0.0)
        self.volum_ratio_dp.setObjectName("volum_ratio_dp")
        self.gridLayout_4.addWidget(self.volum_ratio_dp, 2, 1, 1, 1)
        self.s_tag_radius_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.s_tag_radius_label.setMinimumSize(QtCore.QSize(200, 25))
        self.s_tag_radius_label.setMaximumSize(QtCore.QSize(400, 40))
        self.s_tag_radius_label.setObjectName("s_tag_radius_label")
        self.gridLayout_4.addWidget(self.s_tag_radius_label, 3, 0, 1, 1)
        self.s_tag_radius_dp = QtWidgets.QDoubleSpinBox(self.interface_wheel_window_gbox)
        self.s_tag_radius_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.s_tag_radius_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.s_tag_radius_dp.setMinimum(0.0)
        self.s_tag_radius_dp.setMaximum(0.2)
        self.s_tag_radius_dp.setSingleStep(0.02)
        self.s_tag_radius_dp.setProperty("value", 0.0)
        self.s_tag_radius_dp.setObjectName("s_tag_radius_dp")
        self.gridLayout_4.addWidget(self.s_tag_radius_dp, 3, 1, 1, 1)
        self.v_tag_radius_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.v_tag_radius_label.setMinimumSize(QtCore.QSize(200, 25))
        self.v_tag_radius_label.setMaximumSize(QtCore.QSize(400, 40))
        self.v_tag_radius_label.setObjectName("v_tag_radius_label")
        self.gridLayout_4.addWidget(self.v_tag_radius_label, 4, 0, 1, 1)
        self.v_tag_radius_dp = QtWidgets.QDoubleSpinBox(self.interface_wheel_window_gbox)
        self.v_tag_radius_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.v_tag_radius_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.v_tag_radius_dp.setMinimum(0.0)
        self.v_tag_radius_dp.setMaximum(0.2)
        self.v_tag_radius_dp.setSingleStep(0.02)
        self.v_tag_radius_dp.setProperty("value", 0.0)
        self.v_tag_radius_dp.setObjectName("v_tag_radius_dp")
        self.gridLayout_4.addWidget(self.v_tag_radius_dp, 4, 1, 1, 1)
        self.wheel_ed_wid_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.wheel_ed_wid_label.setMinimumSize(QtCore.QSize(200, 25))
        self.wheel_ed_wid_label.setMaximumSize(QtCore.QSize(400, 40))
        self.wheel_ed_wid_label.setObjectName("wheel_ed_wid_label")
        self.gridLayout_4.addWidget(self.wheel_ed_wid_label, 5, 0, 1, 1)
        self.wheel_ed_wid_sp = QtWidgets.QSpinBox(self.interface_wheel_window_gbox)
        self.wheel_ed_wid_sp.setMinimumSize(QtCore.QSize(60, 25))
        self.wheel_ed_wid_sp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wheel_ed_wid_sp.setMinimum(0)
        self.wheel_ed_wid_sp.setMaximum(20)
        self.wheel_ed_wid_sp.setProperty("value", 0)
        self.wheel_ed_wid_sp.setObjectName("wheel_ed_wid_sp")
        self.gridLayout_4.addWidget(self.wheel_ed_wid_sp, 5, 1, 1, 1)
        self.wheel_ed_color_label = QtWidgets.QLabel(self.interface_wheel_window_gbox)
        self.wheel_ed_color_label.setMinimumSize(QtCore.QSize(200, 25))
        self.wheel_ed_color_label.setMaximumSize(QtCore.QSize(400, 40))
        self.wheel_ed_color_label.setObjectName("wheel_ed_color_label")
        self.gridLayout_4.addWidget(self.wheel_ed_color_label, 6, 0, 1, 1)
        self.wheel_ed_color_0_dp = QtWidgets.QSpinBox(self.interface_wheel_window_gbox)
        self.wheel_ed_color_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.wheel_ed_color_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wheel_ed_color_0_dp.setMaximum(255)
        self.wheel_ed_color_0_dp.setObjectName("wheel_ed_color_0_dp")
        self.gridLayout_4.addWidget(self.wheel_ed_color_0_dp, 6, 1, 1, 1)
        self.wheel_ed_color_1_dp = QtWidgets.QSpinBox(self.interface_wheel_window_gbox)
        self.wheel_ed_color_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.wheel_ed_color_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wheel_ed_color_1_dp.setMaximum(255)
        self.wheel_ed_color_1_dp.setObjectName("wheel_ed_color_1_dp")
        self.gridLayout_4.addWidget(self.wheel_ed_color_1_dp, 6, 2, 1, 1)
        self.wheel_ed_color_2_dp = QtWidgets.QSpinBox(self.interface_wheel_window_gbox)
        self.wheel_ed_color_2_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.wheel_ed_color_2_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.wheel_ed_color_2_dp.setMaximum(255)
        self.wheel_ed_color_2_dp.setObjectName("wheel_ed_color_2_dp")
        self.gridLayout_4.addWidget(self.wheel_ed_color_2_dp, 6, 3, 1, 1)
        self.verticalLayout.addWidget(self.interface_wheel_window_gbox)
        self.interface_image_window_gbox = QtWidgets.QGroupBox(self.setti_scroll_contents)
        self.interface_image_window_gbox.setObjectName("interface_image_window_gbox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.interface_image_window_gbox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.circle_dist_label = QtWidgets.QLabel(self.interface_image_window_gbox)
        self.circle_dist_label.setMinimumSize(QtCore.QSize(200, 25))
        self.circle_dist_label.setMaximumSize(QtCore.QSize(400, 40))
        self.circle_dist_label.setObjectName("circle_dist_label")
        self.gridLayout_12.addWidget(self.circle_dist_label, 0, 0, 1, 1)
        self.circle_dist_sp = QtWidgets.QSpinBox(self.interface_image_window_gbox)
        self.circle_dist_sp.setMinimumSize(QtCore.QSize(60, 25))
        self.circle_dist_sp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.circle_dist_sp.setMaximum(50)
        self.circle_dist_sp.setObjectName("circle_dist_sp")
        self.gridLayout_12.addWidget(self.circle_dist_sp, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.interface_image_window_gbox)
        self.widget.setMinimumSize(QtCore.QSize(60, 25))
        self.widget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout_12.addWidget(self.widget, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.interface_image_window_gbox)
        self.widget_2.setMinimumSize(QtCore.QSize(60, 25))
        self.widget_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_12.addWidget(self.widget_2, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.interface_image_window_gbox)
        self.interface_depot_window_gbox = QtWidgets.QGroupBox(self.setti_scroll_contents)
        self.interface_depot_window_gbox.setObjectName("interface_depot_window_gbox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.interface_depot_window_gbox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.coset_ratio_label = QtWidgets.QLabel(self.interface_depot_window_gbox)
        self.coset_ratio_label.setMinimumSize(QtCore.QSize(200, 25))
        self.coset_ratio_label.setMaximumSize(QtCore.QSize(400, 40))
        self.coset_ratio_label.setObjectName("coset_ratio_label")
        self.gridLayout_13.addWidget(self.coset_ratio_label, 0, 0, 1, 1)
        self.coset_ratio_dp = QtWidgets.QDoubleSpinBox(self.interface_depot_window_gbox)
        self.coset_ratio_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.coset_ratio_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.coset_ratio_dp.setMinimum(0.0)
        self.coset_ratio_dp.setMaximum(1.0)
        self.coset_ratio_dp.setSingleStep(0.1)
        self.coset_ratio_dp.setProperty("value", 0.0)
        self.coset_ratio_dp.setObjectName("coset_ratio_dp")
        self.gridLayout_13.addWidget(self.coset_ratio_dp, 0, 1, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.interface_depot_window_gbox)
        self.widget_3.setMinimumSize(QtCore.QSize(60, 25))
        self.widget_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_13.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.interface_depot_window_gbox)
        self.widget_4.setMinimumSize(QtCore.QSize(60, 25))
        self.widget_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_13.addWidget(self.widget_4, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.interface_depot_window_gbox)
        self.setti_scroll_area.setWidget(self.setti_scroll_contents)
        self.gridLayout_2.addWidget(self.setti_scroll_area, 0, 0, 1, 1)
        self.setti_items.addTab(self.setti_interface, "")
        self.setti_rule = QtWidgets.QWidget()
        self.setti_rule.setObjectName("setti_rule")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.setti_rule)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rule_scroll_area = QtWidgets.QScrollArea(self.setti_rule)
        self.rule_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.rule_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rule_scroll_area.setWidgetResizable(True)
        self.rule_scroll_area.setObjectName("rule_scroll_area")
        self.rule_scroll_contents = QtWidgets.QWidget()
        self.rule_scroll_contents.setGeometry(QtCore.QRect(0, 0, 527, 543))
        self.rule_scroll_contents.setObjectName("rule_scroll_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rule_scroll_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rule_wheel_window_gbox = QtWidgets.QGroupBox(self.rule_scroll_contents)
        self.rule_wheel_window_gbox.setObjectName("rule_wheel_window_gbox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.rule_wheel_window_gbox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.h_range_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.h_range_label.setMinimumSize(QtCore.QSize(200, 25))
        self.h_range_label.setMaximumSize(QtCore.QSize(400, 40))
        self.h_range_label.setObjectName("h_range_label")
        self.gridLayout_7.addWidget(self.h_range_label, 0, 0, 1, 1)
        self.h_range_0_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.h_range_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.h_range_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.h_range_0_dp.setMaximum(360.0)
        self.h_range_0_dp.setSingleStep(10.0)
        self.h_range_0_dp.setObjectName("h_range_0_dp")
        self.gridLayout_7.addWidget(self.h_range_0_dp, 0, 1, 1, 1)
        self.h_range_to_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.h_range_to_label.setMinimumSize(QtCore.QSize(30, 20))
        self.h_range_to_label.setMaximumSize(QtCore.QSize(30, 40))
        self.h_range_to_label.setObjectName("h_range_to_label")
        self.gridLayout_7.addWidget(self.h_range_to_label, 0, 2, 1, 1)
        self.h_range_1_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.h_range_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.h_range_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.h_range_1_dp.setMaximum(360.0)
        self.h_range_1_dp.setSingleStep(10.0)
        self.h_range_1_dp.setProperty("value", 0.0)
        self.h_range_1_dp.setObjectName("h_range_1_dp")
        self.gridLayout_7.addWidget(self.h_range_1_dp, 0, 3, 1, 1)
        self.s_range_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.s_range_label.setMinimumSize(QtCore.QSize(200, 25))
        self.s_range_label.setMaximumSize(QtCore.QSize(400, 40))
        self.s_range_label.setObjectName("s_range_label")
        self.gridLayout_7.addWidget(self.s_range_label, 1, 0, 1, 1)
        self.s_range_0_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.s_range_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.s_range_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.s_range_0_dp.setMaximum(1.0)
        self.s_range_0_dp.setSingleStep(0.1)
        self.s_range_0_dp.setObjectName("s_range_0_dp")
        self.gridLayout_7.addWidget(self.s_range_0_dp, 1, 1, 1, 1)
        self.s_range_to_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.s_range_to_label.setMinimumSize(QtCore.QSize(30, 20))
        self.s_range_to_label.setMaximumSize(QtCore.QSize(30, 40))
        self.s_range_to_label.setObjectName("s_range_to_label")
        self.gridLayout_7.addWidget(self.s_range_to_label, 1, 2, 1, 1)
        self.s_range_1_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.s_range_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.s_range_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.s_range_1_dp.setMaximum(1.0)
        self.s_range_1_dp.setSingleStep(0.1)
        self.s_range_1_dp.setProperty("value", 0.0)
        self.s_range_1_dp.setObjectName("s_range_1_dp")
        self.gridLayout_7.addWidget(self.s_range_1_dp, 1, 3, 1, 1)
        self.v_range_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.v_range_label.setMinimumSize(QtCore.QSize(200, 25))
        self.v_range_label.setMaximumSize(QtCore.QSize(400, 40))
        self.v_range_label.setObjectName("v_range_label")
        self.gridLayout_7.addWidget(self.v_range_label, 2, 0, 1, 1)
        self.v_range_0_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.v_range_0_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.v_range_0_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.v_range_0_dp.setMaximum(1.0)
        self.v_range_0_dp.setSingleStep(0.1)
        self.v_range_0_dp.setObjectName("v_range_0_dp")
        self.gridLayout_7.addWidget(self.v_range_0_dp, 2, 1, 1, 1)
        self.v_range_to_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.v_range_to_label.setMinimumSize(QtCore.QSize(30, 20))
        self.v_range_to_label.setMaximumSize(QtCore.QSize(30, 40))
        self.v_range_to_label.setObjectName("v_range_to_label")
        self.gridLayout_7.addWidget(self.v_range_to_label, 2, 2, 1, 1)
        self.v_range_1_dp = QtWidgets.QDoubleSpinBox(self.rule_wheel_window_gbox)
        self.v_range_1_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.v_range_1_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.v_range_1_dp.setMaximum(1.0)
        self.v_range_1_dp.setSingleStep(0.1)
        self.v_range_1_dp.setProperty("value", 0.0)
        self.v_range_1_dp.setObjectName("v_range_1_dp")
        self.gridLayout_7.addWidget(self.v_range_1_dp, 2, 3, 1, 1)
        self.hm_rule_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.hm_rule_label.setMinimumSize(QtCore.QSize(200, 25))
        self.hm_rule_label.setMaximumSize(QtCore.QSize(400, 40))
        self.hm_rule_label.setObjectName("hm_rule_label")
        self.gridLayout_7.addWidget(self.hm_rule_label, 3, 0, 1, 1)
        self.hm_rule_comb = QtWidgets.QComboBox(self.rule_wheel_window_gbox)
        self.hm_rule_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.hm_rule_comb.setMaximumSize(QtCore.QSize(240, 16777215))
        self.hm_rule_comb.setObjectName("hm_rule_comb")
        self.gridLayout_7.addWidget(self.hm_rule_comb, 3, 1, 1, 2)
        self.overflow_label = QtWidgets.QLabel(self.rule_wheel_window_gbox)
        self.overflow_label.setMinimumSize(QtCore.QSize(200, 25))
        self.overflow_label.setMaximumSize(QtCore.QSize(400, 40))
        self.overflow_label.setObjectName("overflow_label")
        self.gridLayout_7.addWidget(self.overflow_label, 4, 0, 1, 1)
        self.overflow_comb = QtWidgets.QComboBox(self.rule_wheel_window_gbox)
        self.overflow_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.overflow_comb.setMaximumSize(QtCore.QSize(240, 16777215))
        self.overflow_comb.setObjectName("overflow_comb")
        self.gridLayout_7.addWidget(self.overflow_comb, 4, 1, 1, 2)
        self.color_wheel_inner_space = QtWidgets.QWidget(self.rule_wheel_window_gbox)
        self.color_wheel_inner_space.setMinimumSize(QtCore.QSize(0, 25))
        self.color_wheel_inner_space.setMaximumSize(QtCore.QSize(16777215, 40))
        self.color_wheel_inner_space.setObjectName("color_wheel_inner_space")
        self.gridLayout_7.addWidget(self.color_wheel_inner_space, 5, 0, 1, 4)
        self.press_move_cbox = QtWidgets.QCheckBox(self.rule_wheel_window_gbox)
        self.press_move_cbox.setMinimumSize(QtCore.QSize(300, 25))
        self.press_move_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.press_move_cbox.setChecked(False)
        self.press_move_cbox.setObjectName("press_move_cbox")
        self.gridLayout_7.addWidget(self.press_move_cbox, 6, 0, 1, 3)
        self.show_rgb_cbox = QtWidgets.QCheckBox(self.rule_wheel_window_gbox)
        self.show_rgb_cbox.setMinimumSize(QtCore.QSize(300, 25))
        self.show_rgb_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.show_rgb_cbox.setChecked(False)
        self.show_rgb_cbox.setObjectName("show_rgb_cbox")
        self.gridLayout_7.addWidget(self.show_rgb_cbox, 7, 0, 1, 3)
        self.show_hsv_cbox = QtWidgets.QCheckBox(self.rule_wheel_window_gbox)
        self.show_hsv_cbox.setMinimumSize(QtCore.QSize(300, 25))
        self.show_hsv_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.show_hsv_cbox.setChecked(False)
        self.show_hsv_cbox.setObjectName("show_hsv_cbox")
        self.gridLayout_7.addWidget(self.show_hsv_cbox, 8, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.rule_wheel_window_gbox)
        self.rule_image_window_gbox = QtWidgets.QGroupBox(self.rule_scroll_contents)
        self.rule_image_window_gbox.setObjectName("rule_image_window_gbox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.rule_image_window_gbox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.zoom_step_label = QtWidgets.QLabel(self.rule_image_window_gbox)
        self.zoom_step_label.setMinimumSize(QtCore.QSize(200, 25))
        self.zoom_step_label.setMaximumSize(QtCore.QSize(400, 40))
        self.zoom_step_label.setObjectName("zoom_step_label")
        self.gridLayout_14.addWidget(self.zoom_step_label, 0, 0, 1, 1)
        self.zoom_step_dp = QtWidgets.QDoubleSpinBox(self.rule_image_window_gbox)
        self.zoom_step_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.zoom_step_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.zoom_step_dp.setMinimum(1.0)
        self.zoom_step_dp.setMaximum(10.0)
        self.zoom_step_dp.setSingleStep(0.05)
        self.zoom_step_dp.setProperty("value", 1.0)
        self.zoom_step_dp.setObjectName("zoom_step_dp")
        self.gridLayout_14.addWidget(self.zoom_step_dp, 0, 1, 1, 1)
        self.move_step_label = QtWidgets.QLabel(self.rule_image_window_gbox)
        self.move_step_label.setMinimumSize(QtCore.QSize(200, 25))
        self.move_step_label.setMaximumSize(QtCore.QSize(400, 40))
        self.move_step_label.setObjectName("move_step_label")
        self.gridLayout_14.addWidget(self.move_step_label, 1, 0, 1, 1)
        self.move_step_dp = QtWidgets.QSpinBox(self.rule_image_window_gbox)
        self.move_step_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.move_step_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.move_step_dp.setMinimum(1)
        self.move_step_dp.setMaximum(100)
        self.move_step_dp.setProperty("value", 1)
        self.move_step_dp.setObjectName("move_step_dp")
        self.gridLayout_14.addWidget(self.move_step_dp, 1, 1, 1, 1)
        self.rand_num_label = QtWidgets.QLabel(self.rule_image_window_gbox)
        self.rand_num_label.setMinimumSize(QtCore.QSize(200, 25))
        self.rand_num_label.setMaximumSize(QtCore.QSize(400, 40))
        self.rand_num_label.setObjectName("rand_num_label")
        self.gridLayout_14.addWidget(self.rand_num_label, 2, 0, 1, 1)
        self.rand_num_sp = QtWidgets.QSpinBox(self.rule_image_window_gbox)
        self.rand_num_sp.setMinimumSize(QtCore.QSize(60, 25))
        self.rand_num_sp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rand_num_sp.setMaximum(1000000000)
        self.rand_num_sp.setObjectName("rand_num_sp")
        self.gridLayout_14.addWidget(self.rand_num_sp, 2, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.rule_image_window_gbox)
        self.widget_5.setMinimumSize(QtCore.QSize(60, 25))
        self.widget_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_14.addWidget(self.widget_5, 2, 2, 1, 1)
        self.color_image_inner_space = QtWidgets.QWidget(self.rule_image_window_gbox)
        self.color_image_inner_space.setMinimumSize(QtCore.QSize(0, 25))
        self.color_image_inner_space.setMaximumSize(QtCore.QSize(16777215, 40))
        self.color_image_inner_space.setObjectName("color_image_inner_space")
        self.gridLayout_14.addWidget(self.color_image_inner_space, 3, 0, 1, 3)
        self.rev_direct_cbox = QtWidgets.QCheckBox(self.rule_image_window_gbox)
        self.rev_direct_cbox.setMinimumSize(QtCore.QSize(300, 25))
        self.rev_direct_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.rev_direct_cbox.setChecked(False)
        self.rev_direct_cbox.setObjectName("rev_direct_cbox")
        self.gridLayout_14.addWidget(self.rev_direct_cbox, 4, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.rule_image_window_gbox)
        self.rule_depot_window_gbox = QtWidgets.QGroupBox(self.rule_scroll_contents)
        self.rule_depot_window_gbox.setObjectName("rule_depot_window_gbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.rule_depot_window_gbox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stab_column_label = QtWidgets.QLabel(self.rule_depot_window_gbox)
        self.stab_column_label.setMinimumSize(QtCore.QSize(200, 25))
        self.stab_column_label.setMaximumSize(QtCore.QSize(400, 40))
        self.stab_column_label.setObjectName("stab_column_label")
        self.gridLayout_8.addWidget(self.stab_column_label, 0, 0, 1, 1)
        self.stab_column_dp = QtWidgets.QSpinBox(self.rule_depot_window_gbox)
        self.stab_column_dp.setMinimumSize(QtCore.QSize(60, 25))
        self.stab_column_dp.setMaximumSize(QtCore.QSize(120, 16777215))
        self.stab_column_dp.setMinimum(1)
        self.stab_column_dp.setMaximum(12)
        self.stab_column_dp.setProperty("value", 1)
        self.stab_column_dp.setObjectName("stab_column_dp")
        self.gridLayout_8.addWidget(self.stab_column_dp, 0, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.rule_depot_window_gbox)
        self.widget_6.setMinimumSize(QtCore.QSize(60, 25))
        self.widget_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_8.addWidget(self.widget_6, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.rule_depot_window_gbox)
        self.rule_scroll_area.setWidget(self.rule_scroll_contents)
        self.gridLayout_5.addWidget(self.rule_scroll_area, 0, 0, 1, 1)
        self.setti_items.addTab(self.setti_rule, "")
        self.setti_system = QtWidgets.QWidget()
        self.setti_system.setObjectName("setti_system")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.setti_system)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.system_scroll_area = QtWidgets.QScrollArea(self.setti_system)
        self.system_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.system_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.system_scroll_area.setWidgetResizable(True)
        self.system_scroll_area.setObjectName("system_scroll_area")
        self.system_scroll_contents = QtWidgets.QWidget()
        self.system_scroll_contents.setGeometry(QtCore.QRect(0, 0, 527, 939))
        self.system_scroll_contents.setObjectName("system_scroll_contents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.system_scroll_contents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.system_display_gbox = QtWidgets.QGroupBox(self.system_scroll_contents)
        self.system_display_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.system_display_gbox.setObjectName("system_display_gbox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.system_display_gbox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.usr_color_ledit = QtWidgets.QLineEdit(self.system_display_gbox)
        self.usr_color_ledit.setMinimumSize(QtCore.QSize(150, 25))
        self.usr_color_ledit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.usr_color_ledit.setObjectName("usr_color_ledit")
        self.gridLayout_10.addWidget(self.usr_color_ledit, 1, 1, 1, 2)
        self.usr_image_ledit = QtWidgets.QLineEdit(self.system_display_gbox)
        self.usr_image_ledit.setMinimumSize(QtCore.QSize(150, 25))
        self.usr_image_ledit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.usr_image_ledit.setObjectName("usr_image_ledit")
        self.gridLayout_10.addWidget(self.usr_image_ledit, 2, 1, 1, 2)
        self.press_act_cbox = QtWidgets.QCheckBox(self.system_display_gbox)
        self.press_act_cbox.setMinimumSize(QtCore.QSize(400, 25))
        self.press_act_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.press_act_cbox.setChecked(False)
        self.press_act_cbox.setObjectName("press_act_cbox")
        self.gridLayout_10.addWidget(self.press_act_cbox, 5, 0, 1, 3)
        self.lang_label = QtWidgets.QLabel(self.system_display_gbox)
        self.lang_label.setMinimumSize(QtCore.QSize(200, 25))
        self.lang_label.setMaximumSize(QtCore.QSize(400, 40))
        self.lang_label.setObjectName("lang_label")
        self.gridLayout_10.addWidget(self.lang_label, 0, 0, 1, 1)
        self.work_space_inner_space_2 = QtWidgets.QWidget(self.system_display_gbox)
        self.work_space_inner_space_2.setMinimumSize(QtCore.QSize(0, 25))
        self.work_space_inner_space_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.work_space_inner_space_2.setObjectName("work_space_inner_space_2")
        self.gridLayout_10.addWidget(self.work_space_inner_space_2, 7, 0, 1, 3)
        self.restore_original_label = QtWidgets.QLabel(self.system_display_gbox)
        self.restore_original_label.setMinimumSize(QtCore.QSize(350, 25))
        self.restore_original_label.setMaximumSize(QtCore.QSize(400, 40))
        self.restore_original_label.setObjectName("restore_original_label")
        self.gridLayout_10.addWidget(self.restore_original_label, 8, 0, 1, 2)
        self.usr_color_label = QtWidgets.QLabel(self.system_display_gbox)
        self.usr_color_label.setMinimumSize(QtCore.QSize(200, 25))
        self.usr_color_label.setMaximumSize(QtCore.QSize(400, 40))
        self.usr_color_label.setObjectName("usr_color_label")
        self.gridLayout_10.addWidget(self.usr_color_label, 1, 0, 1, 1)
        self.lang_comb = QtWidgets.QComboBox(self.system_display_gbox)
        self.lang_comb.setMinimumSize(QtCore.QSize(150, 25))
        self.lang_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.lang_comb.setObjectName("lang_comb")
        self.gridLayout_10.addWidget(self.lang_comb, 0, 1, 1, 2)
        self.clean_up_btn = QtWidgets.QPushButton(self.system_display_gbox)
        self.clean_up_btn.setMinimumSize(QtCore.QSize(60, 50))
        self.clean_up_btn.setMaximumSize(QtCore.QSize(160, 16777215))
        self.clean_up_btn.setObjectName("clean_up_btn")
        self.gridLayout_10.addWidget(self.clean_up_btn, 9, 2, 1, 1)
        self.restore_original_btn = QtWidgets.QPushButton(self.system_display_gbox)
        self.restore_original_btn.setMinimumSize(QtCore.QSize(60, 50))
        self.restore_original_btn.setMaximumSize(QtCore.QSize(160, 16777215))
        self.restore_original_btn.setObjectName("restore_original_btn")
        self.gridLayout_10.addWidget(self.restore_original_btn, 8, 2, 1, 1)
        self.clean_up_label = QtWidgets.QLabel(self.system_display_gbox)
        self.clean_up_label.setMinimumSize(QtCore.QSize(350, 25))
        self.clean_up_label.setMaximumSize(QtCore.QSize(400, 40))
        self.clean_up_label.setObjectName("clean_up_label")
        self.gridLayout_10.addWidget(self.clean_up_label, 9, 0, 1, 2)
        self.work_space_inner_space_1 = QtWidgets.QWidget(self.system_display_gbox)
        self.work_space_inner_space_1.setMinimumSize(QtCore.QSize(0, 25))
        self.work_space_inner_space_1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.work_space_inner_space_1.setObjectName("work_space_inner_space_1")
        self.gridLayout_10.addWidget(self.work_space_inner_space_1, 3, 0, 1, 3)
        self.win_on_top_cbox = QtWidgets.QCheckBox(self.system_display_gbox)
        self.win_on_top_cbox.setMinimumSize(QtCore.QSize(400, 25))
        self.win_on_top_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.win_on_top_cbox.setChecked(False)
        self.win_on_top_cbox.setObjectName("win_on_top_cbox")
        self.gridLayout_10.addWidget(self.win_on_top_cbox, 6, 0, 1, 3)
        self.usr_image_label = QtWidgets.QLabel(self.system_display_gbox)
        self.usr_image_label.setMinimumSize(QtCore.QSize(200, 25))
        self.usr_image_label.setMaximumSize(QtCore.QSize(400, 40))
        self.usr_image_label.setObjectName("usr_image_label")
        self.gridLayout_10.addWidget(self.usr_image_label, 2, 0, 1, 1)
        self.store_loc_cbox = QtWidgets.QCheckBox(self.system_display_gbox)
        self.store_loc_cbox.setMinimumSize(QtCore.QSize(400, 25))
        self.store_loc_cbox.setMaximumSize(QtCore.QSize(400, 40))
        self.store_loc_cbox.setChecked(False)
        self.store_loc_cbox.setObjectName("store_loc_cbox")
        self.gridLayout_10.addWidget(self.store_loc_cbox, 4, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.system_display_gbox)
        self.groupBox = QtWidgets.QGroupBox(self.system_scroll_contents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.bakgd_id_label = QtWidgets.QLabel(self.groupBox)
        self.bakgd_id_label.setMinimumSize(QtCore.QSize(200, 25))
        self.bakgd_id_label.setMaximumSize(QtCore.QSize(400, 40))
        self.bakgd_id_label.setObjectName("bakgd_id_label")
        self.gridLayout_11.addWidget(self.bakgd_id_label, 0, 0, 1, 1)
        self.bakgd_id_comb = QtWidgets.QComboBox(self.groupBox)
        self.bakgd_id_comb.setMinimumSize(QtCore.QSize(150, 25))
        self.bakgd_id_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.bakgd_id_comb.setObjectName("bakgd_id_comb")
        self.gridLayout_11.addWidget(self.bakgd_id_comb, 0, 1, 1, 1)
        self.style_id_label = QtWidgets.QLabel(self.groupBox)
        self.style_id_label.setMinimumSize(QtCore.QSize(200, 25))
        self.style_id_label.setMaximumSize(QtCore.QSize(400, 40))
        self.style_id_label.setObjectName("style_id_label")
        self.gridLayout_11.addWidget(self.style_id_label, 1, 0, 1, 1)
        self.style_id_comb = QtWidgets.QComboBox(self.groupBox)
        self.style_id_comb.setMinimumSize(QtCore.QSize(150, 25))
        self.style_id_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.style_id_comb.setObjectName("style_id_comb")
        self.gridLayout_11.addWidget(self.style_id_comb, 1, 1, 1, 1)
        self.font_weight_comb = QtWidgets.QComboBox(self.groupBox)
        self.font_weight_comb.setMinimumSize(QtCore.QSize(150, 25))
        self.font_weight_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.font_weight_comb.setObjectName("font_weight_comb")
        self.gridLayout_11.addWidget(self.font_weight_comb, 2, 1, 1, 1)
        self.font_weight_label = QtWidgets.QLabel(self.groupBox)
        self.font_weight_label.setMinimumSize(QtCore.QSize(200, 25))
        self.font_weight_label.setMaximumSize(QtCore.QSize(400, 40))
        self.font_weight_label.setObjectName("font_weight_label")
        self.gridLayout_11.addWidget(self.font_weight_label, 2, 0, 1, 1)
        self.font_family_ledit = QtWidgets.QLineEdit(self.groupBox)
        self.font_family_ledit.setMinimumSize(QtCore.QSize(200, 25))
        self.font_family_ledit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.font_family_ledit.setObjectName("font_family_ledit")
        self.gridLayout_11.addWidget(self.font_family_ledit, 4, 1, 1, 1)
        self.font_size_sp = QtWidgets.QSpinBox(self.groupBox)
        self.font_size_sp.setMinimumSize(QtCore.QSize(150, 25))
        self.font_size_sp.setMaximumSize(QtCore.QSize(360, 16777215))
        self.font_size_sp.setMinimum(4)
        self.font_size_sp.setMaximum(64)
        self.font_size_sp.setObjectName("font_size_sp")
        self.gridLayout_11.addWidget(self.font_size_sp, 3, 1, 1, 1)
        self.font_size_label = QtWidgets.QLabel(self.groupBox)
        self.font_size_label.setMinimumSize(QtCore.QSize(200, 25))
        self.font_size_label.setMaximumSize(QtCore.QSize(400, 40))
        self.font_size_label.setObjectName("font_size_label")
        self.gridLayout_11.addWidget(self.font_size_label, 3, 0, 1, 1)
        self.font_family_label = QtWidgets.QLabel(self.groupBox)
        self.font_family_label.setMinimumSize(QtCore.QSize(200, 25))
        self.font_family_label.setMaximumSize(QtCore.QSize(400, 40))
        self.font_family_label.setObjectName("font_family_label")
        self.gridLayout_11.addWidget(self.font_family_label, 4, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.system_output_gbox = QtWidgets.QGroupBox(self.system_scroll_contents)
        self.system_output_gbox.setObjectName("system_output_gbox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.system_output_gbox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.max_history_files_label = QtWidgets.QLabel(self.system_output_gbox)
        self.max_history_files_label.setMinimumSize(QtCore.QSize(200, 25))
        self.max_history_files_label.setMaximumSize(QtCore.QSize(400, 40))
        self.max_history_files_label.setObjectName("max_history_files_label")
        self.gridLayout_15.addWidget(self.max_history_files_label, 0, 0, 1, 1)
        self.max_history_files_sp = QtWidgets.QSpinBox(self.system_output_gbox)
        self.max_history_files_sp.setMinimumSize(QtCore.QSize(120, 25))
        self.max_history_files_sp.setMaximumSize(QtCore.QSize(360, 16777215))
        self.max_history_files_sp.setMaximum(1000)
        self.max_history_files_sp.setObjectName("max_history_files_sp")
        self.gridLayout_15.addWidget(self.max_history_files_sp, 0, 1, 1, 2)
        self.max_history_steps_label = QtWidgets.QLabel(self.system_output_gbox)
        self.max_history_steps_label.setMinimumSize(QtCore.QSize(200, 25))
        self.max_history_steps_label.setMaximumSize(QtCore.QSize(400, 40))
        self.max_history_steps_label.setObjectName("max_history_steps_label")
        self.gridLayout_15.addWidget(self.max_history_steps_label, 1, 0, 1, 1)
        self.max_history_steps_sp = QtWidgets.QSpinBox(self.system_output_gbox)
        self.max_history_steps_sp.setMinimumSize(QtCore.QSize(120, 25))
        self.max_history_steps_sp.setMaximumSize(QtCore.QSize(360, 16777215))
        self.max_history_steps_sp.setMaximum(1000)
        self.max_history_steps_sp.setObjectName("max_history_steps_sp")
        self.gridLayout_15.addWidget(self.max_history_steps_sp, 1, 1, 1, 2)
        self.work_space_inner_space_3 = QtWidgets.QWidget(self.system_output_gbox)
        self.work_space_inner_space_3.setMinimumSize(QtCore.QSize(0, 25))
        self.work_space_inner_space_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.work_space_inner_space_3.setObjectName("work_space_inner_space_3")
        self.gridLayout_15.addWidget(self.work_space_inner_space_3, 2, 0, 1, 4)
        self.export_ase_type_label = QtWidgets.QLabel(self.system_output_gbox)
        self.export_ase_type_label.setMinimumSize(QtCore.QSize(200, 25))
        self.export_ase_type_label.setMaximumSize(QtCore.QSize(400, 40))
        self.export_ase_type_label.setObjectName("export_ase_type_label")
        self.gridLayout_15.addWidget(self.export_ase_type_label, 3, 0, 1, 1)
        self.export_ase_type_comb = QtWidgets.QComboBox(self.system_output_gbox)
        self.export_ase_type_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.export_ase_type_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.export_ase_type_comb.setObjectName("export_ase_type_comb")
        self.gridLayout_15.addWidget(self.export_ase_type_comb, 3, 1, 1, 3)
        self.export_swatch_ctp_label = QtWidgets.QLabel(self.system_output_gbox)
        self.export_swatch_ctp_label.setMinimumSize(QtCore.QSize(200, 25))
        self.export_swatch_ctp_label.setMaximumSize(QtCore.QSize(400, 40))
        self.export_swatch_ctp_label.setObjectName("export_swatch_ctp_label")
        self.gridLayout_15.addWidget(self.export_swatch_ctp_label, 4, 0, 1, 1)
        self.export_swatch_ctp_comb = QtWidgets.QComboBox(self.system_output_gbox)
        self.export_swatch_ctp_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.export_swatch_ctp_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.export_swatch_ctp_comb.setObjectName("export_swatch_ctp_comb")
        self.gridLayout_15.addWidget(self.export_swatch_ctp_comb, 4, 1, 1, 3)
        self.white_illuminant_label = QtWidgets.QLabel(self.system_output_gbox)
        self.white_illuminant_label.setMinimumSize(QtCore.QSize(200, 25))
        self.white_illuminant_label.setMaximumSize(QtCore.QSize(400, 40))
        self.white_illuminant_label.setObjectName("white_illuminant_label")
        self.gridLayout_15.addWidget(self.white_illuminant_label, 5, 0, 1, 1)
        self.white_illuminant_comb = QtWidgets.QComboBox(self.system_output_gbox)
        self.white_illuminant_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.white_illuminant_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.white_illuminant_comb.setObjectName("white_illuminant_comb")
        self.gridLayout_15.addWidget(self.white_illuminant_comb, 5, 1, 1, 3)
        self.white_observer_label = QtWidgets.QLabel(self.system_output_gbox)
        self.white_observer_label.setMinimumSize(QtCore.QSize(200, 25))
        self.white_observer_label.setMaximumSize(QtCore.QSize(400, 40))
        self.white_observer_label.setObjectName("white_observer_label")
        self.gridLayout_15.addWidget(self.white_observer_label, 6, 0, 1, 1)
        self.white_observer_comb = QtWidgets.QComboBox(self.system_output_gbox)
        self.white_observer_comb.setMinimumSize(QtCore.QSize(120, 25))
        self.white_observer_comb.setMaximumSize(QtCore.QSize(360, 16777215))
        self.white_observer_comb.setObjectName("white_observer_comb")
        self.gridLayout_15.addWidget(self.white_observer_comb, 6, 1, 1, 3)
        self.export_grid_extns_label = QtWidgets.QLabel(self.system_output_gbox)
        self.export_grid_extns_label.setMinimumSize(QtCore.QSize(200, 25))
        self.export_grid_extns_label.setMaximumSize(QtCore.QSize(400, 40))
        self.export_grid_extns_label.setObjectName("export_grid_extns_label")
        self.gridLayout_15.addWidget(self.export_grid_extns_label, 7, 0, 1, 1)
        self.export_grid_extns_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.export_grid_extns_ledit.setMinimumSize(QtCore.QSize(120, 25))
        self.export_grid_extns_ledit.setMaximumSize(QtCore.QSize(360, 16777215))
        self.export_grid_extns_ledit.setObjectName("export_grid_extns_ledit")
        self.gridLayout_15.addWidget(self.export_grid_extns_ledit, 7, 1, 1, 3)
        self.work_space_inner_space_4 = QtWidgets.QWidget(self.system_output_gbox)
        self.work_space_inner_space_4.setMinimumSize(QtCore.QSize(0, 25))
        self.work_space_inner_space_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.work_space_inner_space_4.setObjectName("work_space_inner_space_4")
        self.gridLayout_15.addWidget(self.work_space_inner_space_4, 8, 0, 1, 4)
        self.r_prefix_label = QtWidgets.QLabel(self.system_output_gbox)
        self.r_prefix_label.setMinimumSize(QtCore.QSize(200, 25))
        self.r_prefix_label.setMaximumSize(QtCore.QSize(400, 40))
        self.r_prefix_label.setObjectName("r_prefix_label")
        self.gridLayout_15.addWidget(self.r_prefix_label, 9, 0, 1, 1)
        self.r_prefix_0_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.r_prefix_0_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.r_prefix_0_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.r_prefix_0_ledit.setObjectName("r_prefix_0_ledit")
        self.gridLayout_15.addWidget(self.r_prefix_0_ledit, 9, 1, 1, 1)
        self.r_prefix_1_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.r_prefix_1_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.r_prefix_1_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.r_prefix_1_ledit.setObjectName("r_prefix_1_ledit")
        self.gridLayout_15.addWidget(self.r_prefix_1_ledit, 9, 2, 1, 1)
        self.rgb_prefix_label = QtWidgets.QLabel(self.system_output_gbox)
        self.rgb_prefix_label.setMinimumSize(QtCore.QSize(200, 25))
        self.rgb_prefix_label.setMaximumSize(QtCore.QSize(400, 40))
        self.rgb_prefix_label.setObjectName("rgb_prefix_label")
        self.gridLayout_15.addWidget(self.rgb_prefix_label, 10, 0, 1, 1)
        self.rgb_prefix_0_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.rgb_prefix_0_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.rgb_prefix_0_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rgb_prefix_0_ledit.setObjectName("rgb_prefix_0_ledit")
        self.gridLayout_15.addWidget(self.rgb_prefix_0_ledit, 10, 1, 1, 1)
        self.rgb_prefix_1_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.rgb_prefix_1_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.rgb_prefix_1_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rgb_prefix_1_ledit.setObjectName("rgb_prefix_1_ledit")
        self.gridLayout_15.addWidget(self.rgb_prefix_1_ledit, 10, 2, 1, 1)
        self.rgb_prefix_2_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.rgb_prefix_2_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.rgb_prefix_2_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.rgb_prefix_2_ledit.setObjectName("rgb_prefix_2_ledit")
        self.gridLayout_15.addWidget(self.rgb_prefix_2_ledit, 10, 3, 1, 1)
        self.hec_prefix_label = QtWidgets.QLabel(self.system_output_gbox)
        self.hec_prefix_label.setMinimumSize(QtCore.QSize(200, 25))
        self.hec_prefix_label.setMaximumSize(QtCore.QSize(400, 40))
        self.hec_prefix_label.setObjectName("hec_prefix_label")
        self.gridLayout_15.addWidget(self.hec_prefix_label, 11, 0, 1, 1)
        self.hec_prefix_0_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.hec_prefix_0_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.hec_prefix_0_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.hec_prefix_0_ledit.setObjectName("hec_prefix_0_ledit")
        self.gridLayout_15.addWidget(self.hec_prefix_0_ledit, 11, 1, 1, 1)
        self.hec_prefix_1_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.hec_prefix_1_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.hec_prefix_1_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.hec_prefix_1_ledit.setObjectName("hec_prefix_1_ledit")
        self.gridLayout_15.addWidget(self.hec_prefix_1_ledit, 11, 2, 1, 1)
        self.lst_prefix_label = QtWidgets.QLabel(self.system_output_gbox)
        self.lst_prefix_label.setMinimumSize(QtCore.QSize(200, 25))
        self.lst_prefix_label.setMaximumSize(QtCore.QSize(400, 40))
        self.lst_prefix_label.setObjectName("lst_prefix_label")
        self.gridLayout_15.addWidget(self.lst_prefix_label, 12, 0, 1, 1)
        self.lst_prefix_0_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.lst_prefix_0_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.lst_prefix_0_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lst_prefix_0_ledit.setObjectName("lst_prefix_0_ledit")
        self.gridLayout_15.addWidget(self.lst_prefix_0_ledit, 12, 1, 1, 1)
        self.lst_prefix_1_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.lst_prefix_1_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.lst_prefix_1_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lst_prefix_1_ledit.setObjectName("lst_prefix_1_ledit")
        self.gridLayout_15.addWidget(self.lst_prefix_1_ledit, 12, 2, 1, 1)
        self.lst_prefix_2_ledit = QtWidgets.QLineEdit(self.system_output_gbox)
        self.lst_prefix_2_ledit.setMinimumSize(QtCore.QSize(68, 25))
        self.lst_prefix_2_ledit.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lst_prefix_2_ledit.setObjectName("lst_prefix_2_ledit")
        self.gridLayout_15.addWidget(self.lst_prefix_2_ledit, 12, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.system_output_gbox)
        self.system_scroll_area.setWidget(self.system_scroll_contents)
        self.gridLayout_6.addWidget(self.system_scroll_area, 0, 0, 1, 1)
        self.setti_items.addTab(self.setti_system, "")
        self.setti_shortcuts = QtWidgets.QWidget()
        self.setti_shortcuts.setObjectName("setti_shortcuts")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.setti_shortcuts)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.shortcuts_scroll_area = QtWidgets.QScrollArea(self.setti_shortcuts)
        self.shortcuts_scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.shortcuts_scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shortcuts_scroll_area.setWidgetResizable(True)
        self.shortcuts_scroll_area.setObjectName("shortcuts_scroll_area")
        self.shortcuts_scroll_contents = QtWidgets.QWidget()
        self.shortcuts_scroll_contents.setGeometry(QtCore.QRect(0, 0, 527, 543))
        self.shortcuts_scroll_contents.setObjectName("shortcuts_scroll_contents")
        self.shortcuts_scroll_area.setWidget(self.shortcuts_scroll_contents)
        self.gridLayout_9.addWidget(self.shortcuts_scroll_area, 0, 0, 1, 1)
        self.setti_items.addTab(self.setti_shortcuts, "")
        self.gridLayout.addWidget(self.setti_items, 0, 0, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.setti_items.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        self.interface_general_window_gbox.setTitle(_translate("SettingsDialog", "General"))
        self.positive_wid_label.setText(_translate("SettingsDialog", "positive wid"))
        self.negative_wid_label.setText(_translate("SettingsDialog", "negative wid"))
        self.positive_color_label.setText(_translate("SettingsDialog", "positive color"))
        self.negative_color_label.setText(_translate("SettingsDialog", "negative color"))
        self.interface_wheel_window_gbox.setTitle(_translate("SettingsDialog", "Wheel"))
        self.cubic_ratio_label.setText(_translate("SettingsDialog", "cubic ratio"))
        self.wheel_ratio_label.setText(_translate("SettingsDialog", "wheel ratio"))
        self.volum_ratio_label.setText(_translate("SettingsDialog", "volum ratio"))
        self.s_tag_radius_label.setText(_translate("SettingsDialog", "s tag radius"))
        self.v_tag_radius_label.setText(_translate("SettingsDialog", "v tag radius"))
        self.wheel_ed_wid_label.setText(_translate("SettingsDialog", "wheel ed wid"))
        self.wheel_ed_color_label.setText(_translate("SettingsDialog", "wheel ed color"))
        self.interface_image_window_gbox.setTitle(_translate("SettingsDialog", "Image"))
        self.circle_dist_label.setText(_translate("SettingsDialog", "circle dist"))
        self.interface_depot_window_gbox.setTitle(_translate("SettingsDialog", "Depot"))
        self.coset_ratio_label.setText(_translate("SettingsDialog", "coset ratio"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_interface), _translate("SettingsDialog", "Interface"))
        self.rule_wheel_window_gbox.setTitle(_translate("SettingsDialog", "Wheel"))
        self.h_range_label.setText(_translate("SettingsDialog", "h range"))
        self.h_range_to_label.setText(_translate("SettingsDialog", "to"))
        self.s_range_label.setText(_translate("SettingsDialog", "s range"))
        self.s_range_to_label.setText(_translate("SettingsDialog", "to"))
        self.v_range_label.setText(_translate("SettingsDialog", "v range"))
        self.v_range_to_label.setText(_translate("SettingsDialog", "to"))
        self.hm_rule_label.setText(_translate("SettingsDialog", "hm rule"))
        self.overflow_label.setText(_translate("SettingsDialog", "overflow"))
        self.press_move_cbox.setText(_translate("SettingsDialog", "press move"))
        self.show_rgb_cbox.setText(_translate("SettingsDialog", "show rgb"))
        self.show_hsv_cbox.setText(_translate("SettingsDialog", "show hsv"))
        self.rule_image_window_gbox.setTitle(_translate("SettingsDialog", "Image"))
        self.zoom_step_label.setText(_translate("SettingsDialog", "zoom step"))
        self.move_step_label.setText(_translate("SettingsDialog", "move step"))
        self.rand_num_label.setText(_translate("SettingsDialog", "rand num"))
        self.rev_direct_cbox.setText(_translate("SettingsDialog", "rev direct"))
        self.rule_depot_window_gbox.setTitle(_translate("SettingsDialog", "Depot"))
        self.stab_column_label.setText(_translate("SettingsDialog", "stab column"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_rule), _translate("SettingsDialog", "Rule"))
        self.system_display_gbox.setTitle(_translate("SettingsDialog", "Display"))
        self.press_act_cbox.setText(_translate("SettingsDialog", "press act"))
        self.lang_label.setText(_translate("SettingsDialog", "lang"))
        self.restore_original_label.setText(_translate("SettingsDialog", "restore to original layout"))
        self.usr_color_label.setText(_translate("SettingsDialog", "usr color"))
        self.clean_up_btn.setText(_translate("SettingsDialog", "clean up"))
        self.restore_original_btn.setText(_translate("SettingsDialog", "restore"))
        self.clean_up_label.setText(_translate("SettingsDialog", "clean up all color sets (irrecoverable)"))
        self.win_on_top_cbox.setText(_translate("SettingsDialog", "win on top"))
        self.usr_image_label.setText(_translate("SettingsDialog", "usr image"))
        self.store_loc_cbox.setText(_translate("SettingsDialog", "store loc"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Theme"))
        self.bakgd_id_label.setText(_translate("SettingsDialog", "bakgd id"))
        self.style_id_label.setText(_translate("SettingsDialog", "style id"))
        self.font_weight_label.setText(_translate("SettingsDialog", "font weight"))
        self.font_size_label.setText(_translate("SettingsDialog", "font size"))
        self.font_family_label.setText(_translate("SettingsDialog", "font family"))
        self.system_output_gbox.setTitle(_translate("SettingsDialog", "Output"))
        self.max_history_files_label.setText(_translate("SettingsDialog", "max history files"))
        self.max_history_steps_label.setText(_translate("SettingsDialog", "max history steps"))
        self.export_ase_type_label.setText(_translate("SettingsDialog", "export ase type"))
        self.export_swatch_ctp_label.setText(_translate("SettingsDialog", "export swatch ctp"))
        self.white_illuminant_label.setText(_translate("SettingsDialog", "white illuminant"))
        self.white_observer_label.setText(_translate("SettingsDialog", "white observer"))
        self.export_grid_extns_label.setText(_translate("SettingsDialog", "export grid extns"))
        self.r_prefix_label.setText(_translate("SettingsDialog", "r prefix"))
        self.rgb_prefix_label.setText(_translate("SettingsDialog", "rgb prefix"))
        self.hec_prefix_label.setText(_translate("SettingsDialog", "hec prefix"))
        self.lst_prefix_label.setText(_translate("SettingsDialog", "lst prefix"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_system), _translate("SettingsDialog", "System"))
        self.setti_items.setTabText(self.setti_items.indexOf(self.setti_shortcuts), _translate("SettingsDialog", "Shortcuts"))


